version: "3.9"

services:

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - ./static:/code/static
      - ./media:/code/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py collectstatic --no-input && 
             gunicorn store_service.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
