# Generated by Django 4.2.8 on 2024-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="session_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="order",
            name="status_payment",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
